**Exercício 1:** Criar array com 10 elementos iguais a 0

In [2]:
import numpy as np
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**Exercício 2:** Criar array com 15 elementos iguais a 1

In [4]:
print(np.ones(15))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


**Exercício 3:** Array com os números pares de 50 até 1, com intervalo de contagem de 2.

In [6]:
print(np.arange(30, 1, -2))

[30 28 26 24 22 20 18 16 14 12 10  8  6  4  2]


**Exercício 4:** Array bidimensional 10x10 com números aleatórios inteiros entre 1 e 100

In [8]:
d = np.random.randint(1,101,size=(10,10))
print(d)

[[ 19  68  12  10  24  84  95  36   3  15]
 [ 61  12  75  24  16  69  45  72  24  77]
 [ 45  10   5  51  31  79   9  65  73  96]
 [ 93  58  63  68  56  55  59  77  68  76]
 [ 89   2  97  68  57  25   4  22  36  14]
 [ 37  35  82  12  89  88  59  56  61  98]
 [ 46  66   3  87  88  66  12  56 100  91]
 [ 89  82  50  32  86  28  96  45  59  23]
 [  3  95  59  49  36  39  89  15  14  96]
 [ 30  95   4  38  38  65  39  52  31  17]]


**Exercício 5:** A série de Fibonacci é formada pela seqüência 1,1,2,3,5,8,13,21,34,55,... 


*   Faça um programa capaz de gerar a série até o n−ésimo termo; 
*   Receba via input "Digite o termo desejado";
*   Mostrar o valor que corresponde ao termo informado.


In [17]:
n = int(input("Que termo deseja encontrar: "))
ultimo=1
penultimo=1

if (n==1) or (n==2):
    print("1")
else:
    count=3
    while count <= n:
        termo = ultimo + penultimo
        penultimo = ultimo
        ultimo = termo
        count += 1
    print(termo)

Que termo deseja encontrar: 10
55


**Exercício 6:** Um número primo é aquele que é dividido apenas por um e por ele mesmo. Entre 0 e 100 existem apenas 25 números primos.

*   Receba via input "Digite um número";
*   Mostrar com "True" ou "False" se o número informado é primo.


In [25]:
def primo(n):
    for val in range(2,n):
        if n % val == 0:
            return False
    return True
n = int(input("Digite um número: "))
primo (n)

Digite um número: 13


True